language: node_js
node_js:
  - "10.7.0"

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/velociraptor:$TRAVIS_BRANCH-$TRAVIS_COMMIT .
  - docker push cjblink1/velociraptor:$TRAVIS_BRANCH-$TRAVIS_COMMIT
