apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: velociraptor-certificate
  namespace: default
spec:
  secretName: velociraptor-certs
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: raptor.cjblink1.pro
  dnsNames:
  - raptor.cjblink1.pro
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - raptor.cjblink1.pro
